services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8501:8501"
    volumes:
      - /c/Users/nithi/OneDrive/Documents/AI/financeAssistant/db:/app/db
    networks:
      - finance_net

networks:
  finance_net:
    external: true
