services:
  chromadb:
    image: chromadb/chroma
    ports:
      - "8008:8000"
    volumes:
      - ./chromadb/vector_store:/chroma
    networks:
      - finance_net

networks:
  finance_net:
    external: true
