version: "3.9"
services:
  backend:
    build:
      context: ./backend
    container_name: finance_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=testdb
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - finance_net

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - finance_db_data:/var/lib/mysql
    networks:
      - finance_net

volumes:
  finance_db_data:

networks:
  finance_net:
