services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - finance_net
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASS: password
      DB_NAME: testdb
    volumes:
      - /c/Users/nithi/OneDrive/Documents/AI/financeAssistant/db:/app/db
      - ./backend/chromadb_data:/app/chromadb_data

networks:
  finance_net:
    external: true
